name: Tag test

on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        description: 'core, artifact, cache, exec, github, glob, http-client, io, tool-cache'

jobs:
  test:
    outputs:
      sha: ${{ steps.commit.outputs.sha }}
      tag: ${{ steps.tag.outputs.tag }}
    runs-on: macos-latest
    steps:
      - name: setup repo
        uses: actions/checkout@v3
      - id: commit
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - id: tag
        run: echo "tag=${{ github.event.inputs.package }}-$(cat packages/tool-cache/package.json | jq .version)" >> "$GITHUB_OUTPUT"
  publish:
    runs-on: macos-latest
    needs: test
    steps:
      - name: foo
        run: echo "foo"
  tag:
    name: "Tag commit with ${{ github.event.inputs.package }}-version"
    runs-on: "macos-latest"
    needs: [test, publish]
    steps:
    - uses: actions/checkout@v3
    - name: Create tag
      uses: actions/github-script@v6
      with:
      script: |
        github.rest.git.createRef({
          owner: context.repo.owner,
          repo: context.repo.repo,
          ref: 'refs/tags/${{ needs.test.outputs.tag }}',
          sha: '${{ needs.test.outputs.sha }}'
        })
    # - name: notify slack on failure
    # if: failure()
    # run: |
    #   curl -X POST -H 'Content-type: application/json' --data '{"text":":pb__failed: Publish of ${{ github.event.inputs.package }} was successful, but failed to tag commit ${{ needs.test.outputs.sha }} with version ${{ needs.test.outputs.tag }}"}' $SLACK_WEBHOOK
    # env:
    #   SLACK_WEBHOOK: ${{ secrets.SLACK }}

